### ISSUE TITLE
I can't call RPC port to wallet

### ISSUE THREAD

**Issue by hainn2504** [electric-cash/electric-cash#21]
Hi Team,

I can't call the RPC port when using the wallet.
Can tell me what the RPC port is, I am using port 8332

**Comment by mtwaro** [comment]
It is by default 8332. Please make sure that you've built your node with wallet functionality (did not use `--disable-wallet` flag) and that your `.conf` file enables you to use RPC. Example of a correct `.conf` file:
```
server=1
rpcport=8332
rpcuser=user
rpcpassword=password
rpcbind=0.0.0.0/0
